# Generated by Django 5.1.3 on 2024-12-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogambo', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, default='default_banner.png', null=True, upload_to='profile_media/banners/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='profile_media/avatars/'),
        ),
    ]
