# Generated by Django 5.1.3 on 2024-12-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogambo', '0008_profile_banner_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=85, null=True),
        ),
    ]
